#!/usr/bin/python3
##
## EPITECH PROJECT, 2023
## 109titration
## File description:
## pH-jump
##

import parse
import csv
import sys
from collections import defaultdict
from os import path

def print_usage():
    print("USAGE")
    print("\t./109titration file")
    print("DESCRIPTION")
    print("\tfile\tacsv file containing \"vol;ph\" lines")

def slope_points(data, a, b):
    return (data["pH"][b] - data["pH"][a]) /\
        (data["vol"][b] - data["vol"][a])

def derivative(data):
    dev = []
    for i in range(1, len(data["pH"]) - 1):
        dev.append(slope_points(data, i + 1, i - 1))
    return dev

def maths(data):
    dev = derivative(data)
    for i in range(len(dev)):
        print(dev[i], data)

def main():
    if len(sys.argv) == 2:
        if sys.argv[1] == "-h":
            print_usage()
        elif path.exists(sys.argv[1]):
            maths(parse.parse_information())
        else:
            raise Exception("Invalid argument/file given.")
    else:
        raise Exception("Invalid amount of arguments.")

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(e, file=sys.stderr)
        exit(84)
