#!/usr/bin/python3
##
## EPITECH PROJECT, 2023
## 109titration
## File description:
## pH-jump
##

import sys
from os import path

def print_usage():
    print("USAGE")
    print("\t./109titration file")
    print("DESCRIPTION")
    print("\tfile\tacsv file containing \"vol;ph\" lines")

def main():
    if len(sys.argv) == 2:
        if sys.argv[1] == "-h":
            print_usage()
        elif path.exists(sys.argv[1]):
            pass
        else:
            raise Exception("Invalid argument/file given.")
    else:
        raise Exception("Invalid amount of arguments.")

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(e, file=sys.stderr)
        exit(84)
